### ISSUE TITLE
Predict error

### ISSUE THREAD

**Issue by lihannan** [mhalushka/miRge#11]
Hi miRge devolopment team,
When i use miRge2.0 predict, the software return an error:
Performing prediction of novel miRNAs...
Start to predict
Traceback (most recent call last):
  File "/data1/linan/software/anaconda2/bin/miRge2.0", line 11, in <module>
    load_entry_point('mirge==2.0', 'console_scripts', 'miRge2.0')()
  File "/data1/linan/software/anaconda2/lib/python2.7/site-packages/mirge/__main__.py", line 626, in main
    screen_precusor_candidates(outfile4+'_modified_selected_sorted_features.tsv', outfile4+'_modified_selected_sorted_features_precusor.str', i, rnafoldCmdTmp)
  File "/data1/linan/software/anaconda2/lib/python2.7/site-packages/mirge/utils/screen_precusor_candidates.py", line 190, in screen_precusor_candidates
    neighborStateLabel = content1.index('neighborState')
ValueError: 'neighborState' is not in list

Blow is my command:
miRge2.0 predict -s SRR1044569.fastq.gz -d miRBase -pb /data1/linan/software/bowtie -lib /data1/linan/software/miRge-master_python/miRge_lib -ps /data1/linan/software/samtools19/bin -pr /data1/linan/software/ViennaRNA249/bin -sp human -ad illumina -ai -gff -cpu 10

I install the software by conda. I can not find what's wrong about it, can you help me?

**Comment by mhalushka** [comment]
Hi.  Sorry about that problem. Can you try one thing and let me know if it works or not.  Instead of using 'predict' can you use 'annotate' and see if that will process.  That would be very helpful to know.

**Comment by lihannan** [comment]
Hi,annote is good, the problem only happen in pridict process. is my environment has problem?

**Comment by lihannan** [comment]
Hi,annote is good, the problem only happen in pridict process. is my environment has problem?

**Comment by mhalushka** [comment]
Ok.  Thank you.  That was very helpful.  We will try to figure out what is wrong with predict and revise.  I have some ideas.
