### ISSUE TITLE
Python 2.7 issue

### ISSUE THREAD

**Issue by qidi-yang** [mhalushka/miRge#12]
Hi, 

I downloaded miRge based on the installation guide. The directories are below:  
bowtie: /opt/bowtie1.1.2/bowtie
samtools: /usr/local/bin (compiled from source, version 1.5)
ViennaRNA: /usr/local/bin

I tried to use the annotation mode but there is an error message coming up all the time and it seems like a python program issue. The gray part in the screenshot below is the command I used and the error message is: "TypeError: __call__() takes exactly 3 arguments (2 given) ".
<img width="659" alt="screen shot 2018-09-26 at 6 15 32 pm" src="https://user-images.githubusercontent.com/43623731/46112549-fc8c5a80-c1b8-11e8-8877-c6187754e5d6.png">

Thank you for your help.

**Comment by mhalushka** [comment]
I don't know why you are getting that error.   That is new to me.  Have you tried to troubleshoot this?  A few options to try...
1) Only process one FASTQ file.
2) Call miRge2.0 from the folder containing the FASTQ files
3) Run it on only 1 CPU
Please let me know if any of those methods change anything.

**Comment by qidi-yang** [comment]
Thank you for these suggestions. I have tried all these three options but the same TypeError came out again. Actually, this command sort of works and creates an empty output directory. Is there any other option for me to test?

**Comment by mhalushka** [comment]
Qidi- Thanks for trying to troubleshoot.  When you said this command sort of works, what is that command?

**Comment by mhalushka** [comment]
Ok.  I was working with Matt and was able to run those 3 files on my system using the same command line set up.  The only clear difference was that I used bowtie 1.1.1.  If that isn't the discrepancy, we can compare python 2.7 versions.  We are using 2.7.14.

**Comment by mhalushka** [comment]
So it seems that the cutadapt version 1.18 may have been the culprit here.  I understand miRge2.0 is not working so I will close this issue.
