### ISSUE TITLE
How to run miRge2.0 annotate

### ISSUE THREAD

**Issue by mtakemura** [mhalushka/miRge#16]
I would like to analyze my miRNA-seq samples using miRge2.0. But when I tried to run miRge2.0, I got the following error message. It would be great if someone helped me to fix this problem. Thanks.

Ubuntu 18.04

**My command**

`miRge2.0 annotate -s ./input.fastq.gz -d miRBase -pb ~/bowtie-1.1.2 -lib ~/miRge.Libs -sp fruitfly -ad illumina -o miRge_out`

**Error message**

Performing quantitation analysis of input.fastq...
Process Worker-2:
Traceback (most recent call last):
  File "/home/masa/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/masa/miniconda2/lib/python2.7/site-packages/mirge/utils/trim_file.py", line 54, in run
    read = modifier(read)
TypeError: __call__() takes exactly 3 arguments (2 given)
It takes: 231.51s

Performing annotation for all of the collasped sequences...
Alignment to library miRNA exited with none-zero status.

Traceback (most recent call last):
  File "/home/masa/miniconda2/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
IOError: [Errno 32] Broken pipe

**Comment by mhalushka** [comment]
This should be an easy fix and has been covered.  I suspect you are using cutadapt v1.18.  If you use the recommended (earlier) version of cutadapt (up to v1.16), it should work fine.

**Comment by mhalushka** [comment]
If that doesn't fix the problem, please let me know.

**Comment by mtakemura** [comment]
Thank you very much for your quick reply. I thought I can install a compatible version of cutadapt for miRge2.0 by using conda. And I didn't realize the error message was mentioned in README.md.

Now I downgraded cutadapt to v1.16 and the program looks working fine. Thank you very much for your help!

**Comment by mhalushka** [comment]
I'm glad to hear that.  I will close this issue.
