### ISSUE TITLE
writeDataToCSV error

### ISSUE THREAD

**Issue by snowlover** [mhalushka/miRge#18]
Summarizing and tabulating results...
Traceback (most recent call last):
site-packages/mirge/utils/writeDataToCSV.py", line 541, in detectMismach
    if target_seq[i] != seqTmp[i]:
IndexError: string index out of range

**Comment by mhalushka** [comment]
Hi.  Thanks.  I haven't seen that issue before.  Can you give me some additional information on what you were trying to do and what your setup  is?

**Comment by snowlover** [comment]
Hi. I really don't know more information about this issue. I used all default paramters to 'annotate' ordinary mirna-seq fastq files ... I didn't expect this error when generating the summary tables ...

**Comment by mhalushka** [comment]
I'm not sure why that has happened.  I haven't seen that problem before. Can you try running it with a different sample and see if that problem recurs?  I wouldn't have expected that error either.

**Comment by snowlover** [comment]
Hi. I only have about 7 samples from the same datasets, it seems they had the same error.
fastq reads are like this:

@HWI-:308:HGL2:1:1101:1458:2076 1:N:0:GCCAAT
NGTCTGAGCGTCGCTTTGGAATTCTCGGGTGCCAAGGAACTCCAGTCACG
+
#<<GGIIIGGIIIGGGIIIGGIIGIIIIGGGIIIIIGGIIIIIIIIGGIG

**Comment by snowlover** [comment]
ok, i thought cutadapt in miRge2 may remove them. thanks.
