### ISSUE TITLE
Exited with none-zero status

### ISSUE THREAD

**Issue by leontienvdbent** [mhalushka/miRge#21]
I'm really excited about using miRge2.0 to analyze my small RNA-seq data, but unfortunately haven't been able to get it to work yet. I've double-checked all the dependencies and cannot find an issue there. This is what happens:

```
$ miRge2.0 annotate -s 20729-001.R1.fastq.gz -pb miniconda2/pkgs/bowtie-1.1.2-py27_0/bin/ -lib miRge.Libs/ -sp human -ad AACTGTAGGCACCATCAAT -cpu 1
Performing quantitation analysis of 20729-001.R1.fastq...
It takes: 271.12s

Performing annotation for all of the collasped sequences...
Alignment to library miRNA exited with none-zero status. 
```

I thought it might have something to do with the fact that there are UMI sequences in my data, but when I try to use the trimmed fastq data, I have the same problem:

```
$ miRge2.0 annotate -s trimmed.R1.s.fastq -pb miniconda2/pkgs/bowtie-1.1.2-py27_0/bin/ -lib miRge.Libs/ -sp human
Performing quantitation analysis of trimmed.R1.s.fastq...
It takes: 0.38s

Performing annotation for all of the collasped sequences...
Alignment to library miRNA exited with none-zero status. 
```

I hope you can help me fix this issue, thanks a lot in advance!

**Comment by leontienvdbent** [comment]
I found out that I specified the wrong directory for the bowtie binary... It seems to work now!

**Comment by mhalushka** [comment]
I'm glad to hear that it is working for you now.
