### ISSUE TITLE
The high proportion Remaining Reads

### ISSUE THREAD

**Issue by tianxiahuihui** [mhalushka/miRge#24]
Hello, annotationReport.pdf showed the result as follow picture, and SeqToAnnot.log showed that # reads that failed to align: 6523447 (99.99%)

![image](https://user-images.githubusercontent.com/7579889/66247991-29703780-e754-11e9-8d5b-3db2692bb0f0.png)

I want to know is there any problem of it?

Thank you.

**Comment by mhalushka** [comment]
You likely have not properly removed an adapter sequence, so it is unable to align properly.  Please check that the adapters have been removed.

**Comment by tianxiahuihui** [comment]
I have removed the adapter sequence, It seems I need to remove 4 base of each sequence.

Thank you.
