### ISSUE TITLE
bowtie can't be found in

### ISSUE THREAD

**Issue by carolynePearl** [mhalushka/miRge#28]
hello,

I have created a new environment with the python=2.7 and installed miRge according the instructions. however, when i run the command i get the error "bowtie can't be found in...Please check it."
i installed bowtie=1.1.2 and run which bowtie and used the path in my command. however, the error still shows. what would i be doing wrong;

command;
(miRge) catugonza@kla-ac-bio-03:~/miRge$ miRge2.0 annotate -s/home/catugonza/miRNA/cbbio-miarma-4c18f6c17c13/ks/raw_reads/iss03.fastq.gz -d miRBase -pb /home/catugonza/miniconda3/envs/miRge/bin/bowtie -lib /home/catugonza/miRge/miRge.Libs -sp human -gff -cpu 1
bowtie can't be found in /home/catugonza/miniconda3/envs/miRge/bin/bowtie. Please check it.

Also tried with;
miRge2.0 annotate -s /home/catugonza/miRNA/cbbio-miarma-4c18f6c17c13/ks/raw_reads/iss03.fastq.gz -d miRBase -pb /home/catugonza/miniconda3/envs/miRge/bin/bowtie-1.1.2 -lib /home/catugonza/miRge/miRge.Libs -sp human -cpu 1
bowtie can't be found in /home/catugonza/miniconda3/envs/miRge/bin/bowtie-1.1.2. Please check it.

**Comment by arunhpatil** [comment]
Hi, thank you for reporting, in order to resolve this, I want to approach this issue in two ways. 

-  Try the command with `-pb /home/catugonza/miniconda3/envs/miRge/bin/`
-  Can you list the directory contents for /home/catugonza/miniconda3/envs/miRge/bin/bowtie-1.1.2 as in `ls -li /path/bowtie-1.1.2`.

**Comment by carolynePearl** [comment]
hello;

1. i tried the command; -pb /home/catugonza/miniconda3/envs/miRge/bin/

Command '-pb' not found, did you mean:

  command 'tpb' from deb tpb
  command 'mpb' from deb mpb

Try: apt install <deb name>

**note; i installed miRge via conda in its own environment .**

2. the contents of;/miniconda3/envs/miRge/bin$ less bowtie


 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Bowtie is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Bowtie.  If not, see <http://www.gnu.org/licenses/>.
"""


import os
import imp
import inspect
import logging



def main():
    logging.basicConfig(level=logging.ERROR,
                        format='%(levelname)s: %(message)s'
                        )
    bin_name            = "bowtie"
    bin_s               = "bowtie-align-s"
    bin_l               = "bowtie-align-l"
    idx_ext_l           = '.1.ebwtl' 
    idx_ext_s           = '.1.ebwt' 
    curr_script         = os.path.realpath(inspect.getsourcefile(main))
    ex_path             = os.path.dirname(curr_script)
    bin_spec            = os.path.join(ex_path,bin_s)
    bld                 = imp.load_source('bowtie-build', os.path.join(ex_path, 'bowtie-build'))
    options,arguments   = bld.build_args()

    if '--verbose' in options:
        logging.getLogger().setLevel(logging.INFO)
        
    if '--debug' in options:
        bin_spec += '-debug'
        bin_l += '-debug'
        
    if '--large-index' in options:
        bin_spec = os.path.join(ex_path, bin_l)
    elif len(arguments) >= 2:
        idx_basename = arguments[-2]
        large_idx_exists = os.path.exists(idx_basename + idx_ext_l)
        small_idx_exists = os.path.exists(idx_basename + idx_ext_s)
        if large_idx_exists and not small_idx_exists:
            logging.info("No small index but a large one is present. Using large index.")
            bin_spec = os.path.join(ex_path,bin_l)
    
    arguments[0] = bin_name
    arguments.insert(1, 'basic-0')
    arguments.insert(1, '--wrapper')
    logging.info('Command: %s %s' %  (bin_spec,' '.join(arguments[1:])))
    os.execv(bin_spec, arguments)        
        
        
if __name__ == "__main__":
    main()


(END)

**Comment by carolynePearl** [comment]
hello;

sorry i hadn't understand your first instruction;

i used this command;
miRge2.0 annotate -s/home/catugonza/miRNA/cbbio-miarma-4c18f6c17c13/ks/raw_reads/iss03.fastq.gz -d miRBase -pb **/home/catugonza/miniconda3/envs/miRge/bin/** -lib /home/catugonza/miRge/miRge.Libs -sp human -gff -cpu 1

without specifying the bowtie and it worked perfectly, 

thank you a bunch!!!!
