### ISSUE TITLE
local variable 'sequence' referenced before assignment

### ISSUE THREAD

**Issue by vivekruhela** [mhalushka/miRge#33]
While running mirge pipeline, I am getting the following error:

`Traceback (most recent call last):
  File "/home/vivek/anaconda3/envs/python_mirge/bin/miRge2.0", line 11, in <module>
    load_entry_point('mirge==2.0', 'console_scripts', 'miRge2.0')()
  File "/home/vivek/anaconda3/envs/python_mirge/lib/python2.7/site-packages/mirge/__main__.py", line 652, in main
    write_novel_report(novelmiRNALListFile, featureFile, clusterFile, rnafoldCmdTmp)
  File "/home/vivek/anaconda3/envs/python_mirge/lib/python2.7/site-packages/mirge/utils/write_novel_report.py", line 788, in write_novel_report
    creatPDF(sampleName, novelmiRNANameNew, clusterNameProbabilityDic[matureMiRNAName], chr, startPos, endPos, strand, armType, readCountSumMatureMiRNA, totalReadCountSum, matureMiRNAPrecusorSeq, matureMiRNAPrecusorStr, matureMiRNASeq, passengerMiRNASeq, f3, f4, matureReadContentlist, passengerReadContentlist)
  File "/home/vivek/anaconda3/envs/python_mirge/lib/python2.7/site-packages/mirge/utils/write_novel_report.py", line 237, in creatPDF
    for i in range(len(sequence)):`

`UnboundLocalError: local variable 'sequence' referenced before assignment`

This error message indicates that novel miRNAs are found but there might be some issues in novel miRNA report generation. Due to this error, I am not able to get sequences and details of novel miRNAs. Please suggest. Thanks.

**Comment by arunhpatil** [comment]
Hi Vivek, 

The sequence is derived from a `ps` file which is an output of RNAfold. Please check if the version of RNAfold you are using is  v2.3.5. Also, if the run has crashed then you can find a file with an extension `.ps` in the sub-folder of miRge output (miRge-date-time\novel_miRNA_user-file_ss.ps), can you share that across to get an idea of why this error has occurred. Thanks.

**Comment by vivekruhela** [comment]
I am using RNAfold version 2.4.14. The subfolder of novel_miRNA is empty. I did not get any crashed report from mirge except this error.

I wrote a bash script for my multisample data:

    for file in $(ls /mnt/disk2/data/compressed_fastq/*.fastq); do
        
        echo "working on $file"
        miRge2.0 predict -s $file -pb Packages1/bowtie-1.2.3-linux-x86_64 -lib mirge2/miRge/miRge.Libs/ -sp human -ps Packages1/samtools/samtools-1.10 -pr Packages1/ViennaRNA-2.4.14/src/bin/ -ad TCCGTTTCTCGCCCGCCAAGG -ai -gff -trf -cpu 4 -spikeIn

Save this as `mirge_pipeline.sh` and run the following command:

    bash mirge_pipeline.sh 1>mirge_pipeline.stdout 2>mirge_pipeline.stderr

I always do this so that I get to know which step is creating problems.

**Comment by arunhpatil** [comment]
Hi Vivek, 

Your bash script idea is great. I see the problem here, it is the `version incompatibility`. Please install [ViennaRNA-2.3.5](https://www.tbi.univie.ac.at/RNA/download/sourcecode/2_3_x/ViennaRNA-2.3.5.tar.gz). 

I can explain the differences in the two versions, 
with ViennaRNA-2.3.5 we look for sequence as follows: 
```
if line.strip() == '/sequence (\\':
	line = infTmp.readline()
	sequence = line.strip()[:-1]

```
and with ViennaRNA-2.4.14
```
if line.strip().startswith('/sequence'):
    line = infTmp.readline()
    sequence = line.strip()[:-1]
```
Let me know if this helps. 

Thank you,
Arun

**Comment by vivekruhela** [comment]
Issue Solved. Thanks.
